"""add ble_devices table

Revision ID: 0012a0d193c4
Revises: 
Create Date: 2026-04-09 09:48:45.500336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0012a0d193c4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ble_devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scanned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('address', sa.String(length=17), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('rssi', sa.Integer(), nullable=True),
    sa.Column('tx_power', sa.Integer(), nullable=True),
    sa.Column('estimated_distance_m', sa.Float(), nullable=True),
    sa.Column('signal_quality_pct', sa.Integer(), nullable=True),
    sa.Column('path_loss_db', sa.Integer(), nullable=True),
    sa.Column('address_type', sa.String(length=10), nullable=True),
    sa.Column('is_apple', sa.Boolean(), nullable=True),
    sa.Column('is_microsoft', sa.Boolean(), nullable=True),
    sa.Column('known_companies', sa.JSON(), nullable=True),
    sa.Column('device_profiles', sa.JSON(), nullable=True),
    sa.Column('service_uuids', sa.JSON(), nullable=True),
    sa.Column('manufacturer_data', sa.JSON(), nullable=True),
    sa.Column('service_data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ble_devices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ble_devices_scanned_at'), ['scanned_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ble_devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ble_devices_scanned_at'))

    op.drop_table('ble_devices')
    # ### end Alembic commands ###
